### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by albanm** [koumoul-dev/simple-directory#10]
Come up with a simple material logo.

Do not overkill as brand configuration will replace this logo most of the time, but still we need something.

**Comment by nicolas-bonnel** [comment]
We could have a SD logo.
 * The S could look [like this](https://www.sketchappsources.com/resources/source-image/android-n-logo-kunalbodke.jpg) (flip & rotate the image)
 * The D could look [like this](https://png.pngtree.com/element_origin_min_pic/00/16/05/1057315f596f79f.jpg) (rotate & remove arrows)

**Comment by albanm** [comment]
I like variations on the well known user logo. Something like [this](https://www.google.fr/search?q=material+user+logo&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjPlqLP0NLaAhXSDuwKHVxyCg8Q_AUICigB&biw=1871&bih=989#imgrc=cH3XQY7qRwlv3M:) of [this](https://www.google.fr/search?q=material+user+logo&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjPlqLP0NLaAhXSDuwKHVxyCg8Q_AUICigB&biw=1871&bih=989#imgrc=PPC4J-DUTkErQM:).

**Comment by albanm** [comment]
The first version will do for now.
